export { default as Home } from './Home';
export { default as Menu } from './Menu';
export { default as ProductDetail } from './ProductDetail';
export { default as Blog } from './Blog';
export { default as Pages } from './Pages';
export { default as Contact } from './Contact';
export { default as Login } from './Login';
export { default as SignUp } from './SignUp';
export { default as Cart } from './Cart';
